controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\DefaultController::index
    methods: ['GET']

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['GET', 'POST']

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: ['GET', 'POST']

app_logout:
    path: /logout

app_set_theme:
    path: /set-theme
    controller: App\Controller\DefaultController::setTheme
    methods: ['POST']

app_set_locale:
    path: /set-locale
    controller: App\Controller\DefaultController::setLocale
    methods: ['POST']